services:
  api:
    build: .
    container_name: fpg_server_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://fpg:fpg@db:5432/fpg_db
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: postgres_db_fpg
    restart: always
    environment:
      POSTGRES_USER: fpg
      POSTGRES_PASSWORD: fpg
      POSTGRES_DB: fpg_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
