services:
  api:
    build:
      context: ..
      dockerfile: fpg-server/Dockerfile
    container_name: fpg_server_api
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./output:/app/output
      - ./app/data/server_config.json:/app/app/data/server_config.json:ro
