"""Simple matplotlib helper for visualising coordinate lists.

The module provides a very small plotting utility used during development to
quickly inspect walls, polygons or point lists generated by the formatter.
The resulting image is written into the same directory as this file so that
running the script manually leaves a PNG alongside the source.
"""

from __future__ import annotations

import itertools
import os
from typing import Dict, Iterable, List, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

Point = Tuple[float, float]
Segment = Tuple[Point, Point]
CollinearLine = List[Point]


def plot_points(points: Iterable[Point], filename: str = "points.png") -> str:
    """Draw a scatter of *points* and save to *filename*.

    Each point is printed to stdout before being plotted.

    Returns:
        The absolute path of the written image file.
    """
    pts = list(points)
    for p in pts:
        print("point", p)

    if not pts:
        raise ValueError("no points to plot")

    xs, ys = zip(*pts)
    fig, ax = plt.subplots()
    ax.scatter(xs, ys)
    ax.set_aspect("equal")
    ax.set_title("Points")
    # finer grid: use unit spacing ticks
    ax.xaxis.set_major_locator(MultipleLocator(1))
    ax.yaxis.set_major_locator(MultipleLocator(1))
    ax.grid(True, which="major", linestyle="--", linewidth=0.5)

    base_dir = os.path.dirname(__file__)
    img_dir = os.path.join(base_dir, "images")
    os.makedirs(img_dir, exist_ok=True)
    outpath = os.path.join(img_dir, filename)
    fig.savefig(outpath)
    plt.close(fig)
    print(f"saved plot to {outpath}")
    return outpath


def plot_segments(segments: Iterable[Segment], filename: str = "segments.png") -> str:
    """Draw line segments and save to *filename*.

    Each segment is printed as a start/end pair.
    """
    segs = list(segments)
    for s in segs:
        print("segment", s)

    if not segs:
        raise ValueError("no segments to plot")

    fig, ax = plt.subplots()
    for (x1, y1), (x2, y2) in segs:
        ax.plot([x1, x2], [y1, y2], "k-")
    ax.set_aspect("equal")
    ax.set_title("Segments")
    ax.xaxis.set_major_locator(MultipleLocator(1))
    ax.yaxis.set_major_locator(MultipleLocator(1))
    ax.grid(True, which="major", linestyle="--", linewidth=0.5)

    base_dir = os.path.dirname(__file__)
    img_dir = os.path.join(base_dir, "images")
    os.makedirs(img_dir, exist_ok=True)
    outpath = os.path.join(img_dir, filename)
    fig.savefig(outpath)
    plt.close(fig)
    print(f"saved plot to {outpath}")
    return outpath




def plot_segment_sets(
    horiz_groups: Dict[float, List[CollinearLine]],
    vert_groups: Dict[float, List[CollinearLine]],
    out_dir: str,
    filename: str = "merged_segments.png",
) -> str:
    """Plot merged collinear lines from horizontal and vertical groups.

    Each distinct collinear line (polyline of 2+ points) receives a unique
    colour.  Horizontal lines are drawn with a dotted line style; vertical
    lines with a dashed line style.

    Args:
        horiz_groups: mapping from y-value to list of collinear polylines.
        vert_groups:  mapping from x-value to list of collinear polylines.
        out_dir:      directory in which the PNG is saved.
        filename:     output file name (must end in ``.png``).

    Returns:
        Absolute path of the saved image.
    """
    # build a flat list of all polylines so we can assign unique colours
    all_lines: List[Tuple[str, CollinearLine]] = []
    for _y, lines in sorted(horiz_groups.items()):
        for line in lines:
            all_lines.append(("h", line))
    for _x, lines in sorted(vert_groups.items()):
        for line in lines:
            all_lines.append(("v", line))

    n = max(len(all_lines), 1)
    # choose a palette large enough; tab20 covers up to 20 distinct hues,
    # fall back to the hsv map for larger sets
    cmap_name = "tab20" if n <= 20 else "hsv"
    cmap = plt.colormaps[cmap_name]
    colors = [cmap(i / n) for i in range(n)]
    color_cycle = itertools.cycle(colors)

    fig, ax = plt.subplots(figsize=(10, 10))

    for orientation, line in all_lines:
        color = next(color_cycle)
        xs = [pt[0] for pt in line]
        ys = [pt[1] for pt in line]
        if orientation == "h":
            ax.plot(xs, ys, linestyle=":", linewidth=2, color=color)
            # mark intermediate points so they are visible
            ax.scatter(xs, ys, color=color, s=20, zorder=5)
        else:
            ax.plot(xs, ys, linestyle="--", linewidth=2, color=color)
            ax.scatter(xs, ys, color=color, s=20, zorder=5)

    ax.set_aspect("equal")
    ax.set_title("Merged segments (dotted=horizontal, dashed=vertical)")
    ax.xaxis.set_major_locator(MultipleLocator(1))
    ax.yaxis.set_major_locator(MultipleLocator(1))
    ax.grid(True, which="major", linestyle="-", linewidth=0.3, alpha=0.4)

    os.makedirs(out_dir, exist_ok=True)
    outpath = os.path.join(out_dir, filename)
    fig.savefig(outpath)
    plt.close(fig)
    print(f"Plot saved: {outpath}")
    return outpath


if __name__ == "__main__":
    # simple demonstration when run as a script
    sample_points = [(0, 0), (1, 2), (2, 1)]
    sample_segments = [((0, 0), (1, 2)), ((1, 2), (2, 1))]
    plot_points(sample_points, filename="points_demo.png")
    plot_segments(sample_segments, filename="segments_demo.png")
    # demo segment sets
