"""Optuna tuning defaults for floor plan generation."""

from app.core.fpg_rooms.config_fpg import (
    ENVELOPE_APPLY_SIDES,
    ENVELOPE_ENABLED,
    ENVELOPE_EXCLUDE_TYPES,
    ENVELOPE_MAX_GAP,
    ENVELOPE_MIN_GAP,
)

# Search space for coverage optimization.
OPTUNA_MIN_COVERAGE_LOW = 0.30
OPTUNA_MIN_COVERAGE_HIGH = 0.50
OPTUNA_MIN_COVERAGE_STEP = 0.05

# Search space for hallway count optimization.
OPTUNA_HALLWAY_COUNT_MIN = 1
OPTUNA_HALLWAY_COUNT_MAX = 3
OPTUNA_HALLWAY_COUNT = 3

# Search jitter around each room's current min/max bounds.
OPTUNA_DIMENSION_MIN_JITTER = 5
OPTUNA_DIMENSION_MAX_JITTER = 10

# Sampling policy thresholds for room placement.
OPTUNA_ROOM_BACK_BAND_DEPTH = 10.0
OPTUNA_ROOM_PROXIMITY_SLACK = 10.0
OPTUNA_NODE_PLACEMENT_SAMPLING_RADIUS = 8.0

# Graph staged-physics defaults for Optuna-only runs.
OPTUNA_GRAPH_PHASE1_UNIFORM_RADIUS = 8.0
OPTUNA_GRAPH_PHASE1_ITERATIONS = 210
OPTUNA_GRAPH_PHASE2_ITERATIONS = 90

# Clamp used when rebuilding requirements from best params.
OPTUNA_MIN_COVERAGE_FLOOR = 0.01

# Common Optuna param names used in this project.
OPTUNA_PARAM_KEY_MIN_COVERAGE = "config_min_coverage"
OPTUNA_PARAM_KEY_HALLWAY_COUNT = "hallway_count"

# Runner defaults.
OPTUNA_DEFAULT_TRIALS = 1
OPTUNA_DEFAULT_STUDY_NAME = "fpg_layout_optimization"

# Envelope fallbacks for mutated configs.
OPTUNA_ENVELOPE_ENABLED_DEFAULT = ENVELOPE_ENABLED
OPTUNA_ENVELOPE_MIN_GAP_DEFAULT = ENVELOPE_MIN_GAP
OPTUNA_ENVELOPE_MAX_GAP_DEFAULT = ENVELOPE_MAX_GAP
OPTUNA_ENVELOPE_EXCLUDE_TYPES_DEFAULT = tuple(ENVELOPE_EXCLUDE_TYPES)
OPTUNA_ENVELOPE_APPLY_SIDES_DEFAULT = tuple(ENVELOPE_APPLY_SIDES)

__all__ = [
    "OPTUNA_MIN_COVERAGE_LOW",
    "OPTUNA_MIN_COVERAGE_HIGH",
    "OPTUNA_MIN_COVERAGE_STEP",
    "OPTUNA_HALLWAY_COUNT_MIN",
    "OPTUNA_HALLWAY_COUNT_MAX",
    "OPTUNA_DIMENSION_MIN_JITTER",
    "OPTUNA_DIMENSION_MAX_JITTER",
    "OPTUNA_ROOM_BACK_BAND_DEPTH",
    "OPTUNA_ROOM_PROXIMITY_SLACK",
    "OPTUNA_NODE_PLACEMENT_SAMPLING_RADIUS",
    "OPTUNA_GRAPH_PHASE1_UNIFORM_RADIUS",
    "OPTUNA_GRAPH_PHASE1_ITERATIONS",
    "OPTUNA_GRAPH_PHASE2_ITERATIONS",
    "OPTUNA_MIN_COVERAGE_FLOOR",
    "OPTUNA_PARAM_KEY_MIN_COVERAGE",
    "OPTUNA_PARAM_KEY_HALLWAY_COUNT",
    "OPTUNA_DEFAULT_TRIALS",
    "OPTUNA_DEFAULT_STUDY_NAME",
    "OPTUNA_ENVELOPE_ENABLED_DEFAULT",
    "OPTUNA_ENVELOPE_MIN_GAP_DEFAULT",
    "OPTUNA_ENVELOPE_MAX_GAP_DEFAULT",
    "OPTUNA_ENVELOPE_EXCLUDE_TYPES_DEFAULT",
    "OPTUNA_ENVELOPE_APPLY_SIDES_DEFAULT",
]
