"""Scoring and validation defaults for floor plan generation."""

from app.core.fpg_rooms.config_fpg import (
    DEFAULT_ADJACENCY_MIN_OVERLAP,
    ENVELOPE_APPLY_SIDES,
    ENVELOPE_EXCLUDE_TYPES,
    ENVELOPE_MAX_GAP,
    ENVELOPE_MIN_GAP,
)

SCORE_VALIDATION_MIN_OVERLAP = DEFAULT_ADJACENCY_MIN_OVERLAP
SCORE_ENVELOPE_MIN_GAP = ENVELOPE_MIN_GAP
SCORE_ENVELOPE_MAX_GAP = ENVELOPE_MAX_GAP
SCORE_ENVELOPE_EXCLUDE_TYPES = tuple(ENVELOPE_EXCLUDE_TYPES)
SCORE_ENVELOPE_APPLY_SIDES = tuple(ENVELOPE_APPLY_SIDES)

__all__ = [
    "SCORE_VALIDATION_MIN_OVERLAP",
    "SCORE_ENVELOPE_MIN_GAP",
    "SCORE_ENVELOPE_MAX_GAP",
    "SCORE_ENVELOPE_EXCLUDE_TYPES",
    "SCORE_ENVELOPE_APPLY_SIDES",
]
