"""Floor plan generation config (shared)."""

# Floor Dimensions (default)
FLOOR_WIDTH = 100
FLOOR_HEIGHT = 150

# Maximum allowed aspect ratio for rooms
MAX_ASPECT_RATIO_HEIGHT = 10
MAX_ASPECT_RATIO_WIDTH = 16

# Minimum floor area coverage (50%)
MIN_COVERAGE = 0.5

# Safety buffer used in pre-validation feasibility checks
SAFETY_BUFFER = 100.0

# Floor-plan scoring weights
SCORE_WEIGHTS = {
    "coverage": 0.40,
    "rectangularity": 0.35,
    "empty_space": 0.25,
}

# Shapely scoring controls
SCORE_GEOMETRY_TOLERANCE = 1e-6
INWARD_POCKET_MAX_LENGTH = 20.0

# Envelope/staircase settings
ENVELOPE_ENABLED = True
ENVELOPE_MIN_GAP = 5
ENVELOPE_MAX_GAP = 20
ENVELOPE_EXCLUDE_TYPES = []
ENVELOPE_APPLY_SIDES = ["left", "right", "top", "bottom"]

# Garage placement settings
GARAGE_SIDE_ANCHOR_THRESHOLD = 20

# Veranda outdoor space bounds
VERANDA_OUTDOOR_SPACE_MIN_W = 1
VERANDA_OUTDOOR_SPACE_MIN_H = 1
VERANDA_OUTDOOR_SPACE_MAX_W = 100
VERANDA_OUTDOOR_SPACE_MAX_H = 100

# Adjacency constraint settings
DEFAULT_ADJACENCY_MIN_OVERLAP = 20
GENERATOR_ADJACENCY_MIN_OVERLAP = 20

# Room location/bathroom preferences
BATHROOM_LOCATION_WEIGHT = 1

# Constraint toggles (hard)
CONSTRAINT_HARD_BASIC_GEOMETRY = True
CONSTRAINT_HARD_HALLWAY_RULES = True
CONSTRAINT_HARD_ROOM_SHARED_WALLS = True
CONSTRAINT_HARD_ROOM_ADJACENCY = True
CONSTRAINT_HARD_MINIMUM_AREA_COVERAGE = True
CONSTRAINT_HARD_ROOM_SIZE_HIERARCHY = True
CONSTRAINT_HARD_LIVING_ROOM_LOCATION = True
CONSTRAINT_HARD_VERANDA_PLACEMENT = True
CONSTRAINT_HARD_GARAGE_PLACEMENT = True
CONSTRAINT_HARD_ENVELOPE_STAIRCASE = True
CONSTRAINT_HARD_KITCHEN_HALLWAY_BACK_WALL_SETBACK = True

# Kitchen/hallway back-wall door setback settings
KITCHEN_HALLWAY_BACK_WALL_SETBACK_MIN_GAP = 5
KITCHEN_HALLWAY_BACK_WALL_SETBACK_MAX_GAP = 20

# Constraint toggles (soft)
CONSTRAINT_SOFT_SEED_LAYOUT_HINTS = True
CONSTRAINT_SOFT_ROOM_ADJACENCY_PREFERENCE = True
CONSTRAINT_SOFT_COMPACT_LAYOUT_CENTER_PROXIMITY = True
CONSTRAINT_SOFT_BATHROOM_LOCATION_PREFERENCE = True
CONSTRAINT_SOFT_LAYOUT_DEAD_SPACE_PENALTY = True
CONSTRAINT_SOFT_SEED_FACADE_DEPTH_PENALTY = True
CONSTRAINT_SOFT_SEED_FACADE_ALIGNMENT_PENALTY = True
CONSTRAINT_SOFT_RECESSED_FACADE_PENALTY = True
CONSTRAINT_SOFT_ROOM_SHARED_WALL_REFINE = True

# Soft-constraint tuning constants
SOFT_LAYOUT_DEAD_SPACE_WEIGHT = 12
SOFT_SEED_FACADE_DEPTH_WEIGHT = 25
SOFT_SEED_FACADE_ALIGNMENT_WEIGHT = 8
SOFT_SEED_FACADE_ALIGNMENT_THRESHOLD = 10
SOFT_RECESSED_FACADE_NEAR_BAND = 45
SOFT_RECESSED_FACADE_BASE_THRESHOLD = 10
SOFT_RECESSED_FACADE_SEVERE_THRESHOLD = 20
SOFT_RECESSED_FACADE_BASE_WEIGHT = 45
SOFT_RECESSED_FACADE_SEVERE_WEIGHT = 140
SOFT_RECESSED_FACADE_ATTACH_WEIGHT = 14
SOFT_RECESSED_FACADE_SIDE_GAP_THRESHOLD = 40
SOFT_ROOM_SHARED_WALL_REFINE_WEIGHT = 50

# Default room size bounds used in normalization/fallback payloads
DEFAULT_MIN_W = 12
DEFAULT_MIN_H = 10
DEFAULT_MAX_W = 70
DEFAULT_MAX_H = 70

# Room size hierarchy (% of living room area)
ROOM_SIZE_HIERARCHY = {
    "bedroom": (50, 70),
    "kitchen": (40, 50),
    "bathroom": (15, 30),
    "attachedBathroom":(15,30),
    "veranda":(40,70),
    "garage":(50,70)
}

# Default solver/optuna execution settings
DEFAULT_ROOM_DIMENSION = 70
DEFAULT_OPTUNA_TRIALS = 20
DEFAULT_OPTUNA_STORAGE_ENABLED = False
DEFAULT_OPTUNA_STUDY_NAME = "FPG_study"
DEFAULT_OPTUNA_STORAGE_URL = "sqlite:///optuna_fpg.db"

# Default generator config
DEFAULT_ASPECT_RATIO_MAX = 16.0
DEFAULT_ASPECT_RATIO_MIN = 0.0
DEFAULT_HALLWAY_COUNT = 1
DEFAULT_SOLVER_MAX_TIME_SECONDS = 5
WIGGLE_ROOM = 10

# Hallway dimensions
# Fixed narrow dimension — the solver enforces exactly this value for
# whichever of width/height is the "short" side.
HALLWAY_WIDTH = 10
# Minimum length of the long side (the solver may extend it further).
HALLWAY_MIN_LENGTH = 10
# Number of hallway walls that must be fully shared with other rooms.
# Default 3 means only one hallway wall may remain as an exterior wall.
HALLWAY_REQUIRED_SHARED_WALLS = 3

# Refine-only living room extender settings
LIVING_ROOM_EXTENDER_REFINE_ONLY_ENABLED = True
LIVING_ROOM_EXTENDER_COUNT = 1
LIVING_ROOM_EXTENDER_MIN_SIZE = 10
LIVING_ROOM_EXTENDER_MAX_SIZE = 30
LIVING_ROOM_EXTENDER_INACTIVE_SIZE_CAP = 9
LIVING_ROOM_EXTENDER_ACTIVATION_PENALTY = 200
LIVING_ROOM_EXTENDER_SINGLE_REFINE_RUN = True

# Room types whose relation constraints should not be pruned by template.
NOT_PRUNE_ROOMS = ["livingRoom", "hallway"]

# Per-type room shared-wall requirements.
# - min_walls/max_walls count fully shared sides.
# - wiggle_pct relaxes minimum shared coverage length across the selected
#   min_walls sides; e.g. 30 means up to 30% uncovered is allowed.
ROOM_SHARED_WALL_RULES = {
    "livingRoom": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 10},
    "bathroom": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 0},
    "bedroom": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 10},
    "kitchen": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 10},
    "attachedBathroom": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 10},
    "veranda": {"min_walls": 1, "max_walls": 3, "wiggle_pct": 10},
    "garage": {"min_walls": 1, "max_walls": 2, "wiggle_pct": 10},
}
# Refinement phase shared-wall rules (tighter minimum requirements for refine_1).
# Applied as soft constraint with penalties for violations.
ROOM_SHARED_WALL_RULES_REFINE = {
    "livingRoom": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 10},
    "bathroom": {"min_walls": 3, "max_walls": 4, "wiggle_pct": 0},
    "bedroom": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 20},
    "kitchen": {"min_walls": 2, "max_walls": 4, "wiggle_pct": 10},
    "attachedBathroom": {"min_walls": 3, "max_walls": 5, "wiggle_pct": 10},
    "veranda": {"min_walls": 1, "max_walls": 3, "wiggle_pct": 10},
    "garage": {"min_walls": 1, "max_walls": 2, "wiggle_pct": 10},
}

__all__ = [
    "FLOOR_WIDTH",
    "FLOOR_HEIGHT",
    "MAX_ASPECT_RATIO_HEIGHT",
    "MAX_ASPECT_RATIO_WIDTH",
    "MIN_COVERAGE",
    "SCORE_WEIGHTS",
    "SCORE_GEOMETRY_TOLERANCE",
    "INWARD_POCKET_MAX_LENGTH",
    "DEFAULT_ADJACENCY_MIN_OVERLAP",
    "GENERATOR_ADJACENCY_MIN_OVERLAP",
    "ENVELOPE_ENABLED",
    "ENVELOPE_MIN_GAP",
    "ENVELOPE_MAX_GAP",
    "ENVELOPE_EXCLUDE_TYPES",
    "ENVELOPE_APPLY_SIDES",
    "BATHROOM_LOCATION_WEIGHT",
    "CONSTRAINT_HARD_BASIC_GEOMETRY",
    "CONSTRAINT_HARD_HALLWAY_RULES",
    "CONSTRAINT_HARD_ROOM_SHARED_WALLS",
    "CONSTRAINT_HARD_ROOM_ADJACENCY",
    "CONSTRAINT_HARD_MINIMUM_AREA_COVERAGE",
    "CONSTRAINT_HARD_ROOM_SIZE_HIERARCHY",
    "CONSTRAINT_HARD_LIVING_ROOM_LOCATION",
    "CONSTRAINT_HARD_VERANDA_PLACEMENT",
    "CONSTRAINT_HARD_GARAGE_PLACEMENT",
    "CONSTRAINT_HARD_ENVELOPE_STAIRCASE",
    "CONSTRAINT_HARD_KITCHEN_HALLWAY_BACK_WALL_SETBACK",
    "KITCHEN_HALLWAY_BACK_WALL_SETBACK_MIN_GAP",
    "KITCHEN_HALLWAY_BACK_WALL_SETBACK_MAX_GAP",
    "CONSTRAINT_SOFT_SEED_LAYOUT_HINTS",
    "CONSTRAINT_SOFT_ROOM_ADJACENCY_PREFERENCE",
    "CONSTRAINT_SOFT_COMPACT_LAYOUT_CENTER_PROXIMITY",
    "CONSTRAINT_SOFT_BATHROOM_LOCATION_PREFERENCE",
    "CONSTRAINT_SOFT_LAYOUT_DEAD_SPACE_PENALTY",
    "CONSTRAINT_SOFT_SEED_FACADE_DEPTH_PENALTY",
    "CONSTRAINT_SOFT_SEED_FACADE_ALIGNMENT_PENALTY",
    "CONSTRAINT_SOFT_RECESSED_FACADE_PENALTY",
    "CONSTRAINT_SOFT_ROOM_SHARED_WALL_REFINE",
    "SOFT_LAYOUT_DEAD_SPACE_WEIGHT",
    "SOFT_SEED_FACADE_DEPTH_WEIGHT",
    "SOFT_SEED_FACADE_ALIGNMENT_WEIGHT",
    "SOFT_SEED_FACADE_ALIGNMENT_THRESHOLD",
    "SOFT_RECESSED_FACADE_NEAR_BAND",
    "SOFT_RECESSED_FACADE_BASE_THRESHOLD",
    "SOFT_RECESSED_FACADE_SEVERE_THRESHOLD",
    "SOFT_RECESSED_FACADE_BASE_WEIGHT",
    "SOFT_RECESSED_FACADE_SEVERE_WEIGHT",
    "SOFT_RECESSED_FACADE_ATTACH_WEIGHT",
    "SOFT_RECESSED_FACADE_SIDE_GAP_THRESHOLD",
    "SOFT_ROOM_SHARED_WALL_REFINE_WEIGHT",
    "DEFAULT_MIN_W",
    "DEFAULT_MIN_H",
    "DEFAULT_MAX_W",
    "DEFAULT_MAX_H",
    "ROOM_SIZE_HIERARCHY",
    "DEFAULT_ROOM_DIMENSION",
    "DEFAULT_OPTUNA_TRIALS",
    "DEFAULT_OPTUNA_STORAGE_ENABLED",
    "DEFAULT_OPTUNA_STORAGE_URL",
    "DEFAULT_ASPECT_RATIO_MAX",
    "DEFAULT_ASPECT_RATIO_MIN",
    "DEFAULT_HALLWAY_COUNT",
    "DEFAULT_SOLVER_MAX_TIME_SECONDS",
    "WIGGLE_ROOM",
    "SAFETY_BUFFER",
    "GARAGE_SIDE_ANCHOR_THRESHOLD",
    "VERANDA_OUTDOOR_SPACE_MIN_W",
    "VERANDA_OUTDOOR_SPACE_MIN_H",
    "VERANDA_OUTDOOR_SPACE_MAX_W",
    "VERANDA_OUTDOOR_SPACE_MAX_H",
    "HALLWAY_WIDTH",
    "HALLWAY_MIN_LENGTH",
    "HALLWAY_REQUIRED_SHARED_WALLS",
    "LIVING_ROOM_EXTENDER_REFINE_ONLY_ENABLED",
    "LIVING_ROOM_EXTENDER_COUNT",
    "LIVING_ROOM_EXTENDER_MIN_SIZE",
    "LIVING_ROOM_EXTENDER_MAX_SIZE",
    "LIVING_ROOM_EXTENDER_INACTIVE_SIZE_CAP",
    "LIVING_ROOM_EXTENDER_ACTIVATION_PENALTY",
    "LIVING_ROOM_EXTENDER_SINGLE_REFINE_RUN",
    "NOT_PRUNE_ROOMS",
    "ROOM_SHARED_WALL_RULES",
    "ROOM_SHARED_WALL_RULES_REFINE",
]
