"""Simple matplotlib helper for visualising coordinate lists.

The module provides a very small plotting utility used during development to
quickly inspect walls, polygons or point lists generated by the formatter.
The resulting image is written into the same directory as this file so that
running the script manually leaves a PNG alongside the source.
"""

from __future__ import annotations

import os
from typing import Iterable, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

Point = Tuple[float, float]
Segment = Tuple[Point, Point]


def plot_points(
    points: Iterable[Point], filename: str = "points.png"
) -> str:
    """Draw a scatter of *points* and save to *filename*.

    Each point is printed to stdout before being plotted.

    Returns:
        The absolute path of the written image file.
    """
    pts = list(points)
    for p in pts:
        print("point", p)

    if not pts:
        raise ValueError("no points to plot")

    xs, ys = zip(*pts)
    fig, ax = plt.subplots()
    ax.scatter(xs, ys)
    ax.set_aspect("equal")
    ax.set_title("Points")
    # finer grid: use unit spacing ticks
    ax.xaxis.set_major_locator(MultipleLocator(1))
    ax.yaxis.set_major_locator(MultipleLocator(1))
    ax.grid(True, which='major', linestyle='--', linewidth=0.5)

    base_dir = os.path.dirname(__file__)
    img_dir = os.path.join(base_dir, "images")
    os.makedirs(img_dir, exist_ok=True)
    outpath = os.path.join(img_dir, filename)
    fig.savefig(outpath)
    plt.close(fig)
    print(f"saved plot to {outpath}")
    return outpath


def plot_segments(
    segments: Iterable[Segment], filename: str = "segments.png"
) -> str:
    """Draw line segments and save to *filename*.

    Each segment is printed as a start/end pair.
    """
    segs = list(segments)
    for s in segs:
        print("segment", s)

    if not segs:
        raise ValueError("no segments to plot")

    fig, ax = plt.subplots()
    for (x1, y1), (x2, y2) in segs:
        ax.plot([x1, x2], [y1, y2], "k-")
    ax.set_aspect("equal")
    ax.set_title("Segments")
    ax.xaxis.set_major_locator(MultipleLocator(1))
    ax.yaxis.set_major_locator(MultipleLocator(1))
    ax.grid(True, which='major', linestyle='--', linewidth=0.5)

    base_dir = os.path.dirname(__file__)
    img_dir = os.path.join(base_dir, "images")
    os.makedirs(img_dir, exist_ok=True)
    outpath = os.path.join(img_dir, filename)
    fig.savefig(outpath)
    plt.close(fig)
    print(f"saved plot to {outpath}")
    return outpath


if __name__ == "__main__":
    # simple demonstration when run as a script
    sample_points = [(0, 0), (1, 2), (2, 1)]
    sample_segments = [((0, 0), (1, 2)), ((1, 2), (2, 1))]
    plot_points(sample_points, filename="points_demo.png")
    plot_segments(sample_segments, filename="segments_demo.png")
