from __future__ import annotations

from typing import Any, Protocol, Sequence

from ortools.sat.python import cp_model


class CpModelLike(Protocol):
    def NewBoolVar(self, name: str) -> cp_model.IntVar: ...

    def NewIntVar(self, lb: int, ub: int, name: str) -> cp_model.IntVar: ...

    def Add(self, constraint: Any) -> Any: ...

    def AddBoolOr(self, literals: Sequence[Any]) -> Any: ...

    def Minimize(self, objective: Any) -> Any: ...

    def Maximize(self, objective: Any) -> Any: ...
