

###
POST http://localhost:8000/algorithms/format/v2
Content-Type: application/json

{
	"floor_width": 150,
	"floor_height": 150,
	"room_template": {
		"name": "Standard 2BHK Layout",
		"data": [
			{ "id": "bedroom1", "type": "bedroom" },
			{ "id": "bedroom2", "type": "bedroom" },
			{ "id": "bathroom1", "type": "bathroom" },
			{ "id": "kitchen1", "type": "kitchen" },
			{ "id": "attachedBathroom1", "type": "attachedBathroom" },
			{ "id": "veranda1", "type": "veranda" },
			{ "id": "garage1", "type": "garage" },
			{ "id": "diningRoom1", "type": "diningRoom" }
			
		]
	},
	"should_optuna_run": true,
	"optuna_trial_count": 100
}

###
POST http://localhost:8000/algorithms/buildable-space
Content-Type: application/json

{
	"area": 100000,
	"segmentsCoordinates": [
		{ "x": 136.35599418843543, "y": 136.5242567940487 },
		{ "x": 483.0349661110454, "y": 209.93862731883672 },
		{ "x": 519.7421513734394, "y": 523.9889901193187 },
		{ "x": 136.35599418843543, "y": 381.2388252100087 },
		{ "x": 136.35599418843543, "y": 136.5242567940487 }
	],
	"roadConnected": [
		{
			"segment": [
				{ "x": 483.0349661110454, "y": 209.93862731883672 },
				{ "x": 519.7421513734394, "y": 523.9889901193187 }
			],
			"roadType": "mainRoad"
		}
	],
	"min_width": 100,
	"min_height": 100,
	"should_plot": true
}
