GET http://localhost:8000/algorithms/format

###
POST http://localhost:8000/algorithms/format/v2
Content-Type: application/json

{
	"floor_width": 500,
	"floor_height": 800,
	"room_template": {
		"name": "Standard 2BHK Layout",
		"data": [
			{ "id": "bedroom1", "type": "bedroom" },
			{ "id": "bedroom2", "type": "bedroom" },
			{ "id": "bathroom1", "type": "bathroom" },
			{ "id": "kitchen1", "type": "kitchen" }
		]
	},
	"should_optuna_run": true,
	"optuna_trial_count": 50
}