from .api import score_floor_plan
from .config import EvaluatorRule, ScoringGroupRule, ScoringProfile
from .context import ScoringContext, ScoringContextFactory
from .defaults import (
    DEFAULT_SCORING_PROFILE,
    create_default_profile,
    create_default_registry,
)
from .evaluators import (
    BEDROOM_QUALITY_KEY,
    ENCLOSED_VOIDS_KEY,
    GEOMETRY_INTEGRITY_KEY,
    INWARD_RECESS_KEY,
    KITCHEN_DINING_KEY,
    LIVING_ROOM_BALANCE_KEY,
    REQUIRED_ADJACENCY_KEY,
    BedroomQualityEvaluator,
    BedroomQualitySettings,
    EnclosedVoidsEvaluator,
    EnclosedVoidsSettings,
    FloorPlanEvaluator,
    GeometryIntegrityEvaluator,
    GeometryIntegritySettings,
    InwardRecessEvaluator,
    InwardRecessSettings,
    KitchenDiningEvaluator,
    KitchenDiningSettings,
    LivingRoomBalanceEvaluator,
    LivingRoomBalanceSettings,
    RequiredAdjacencyEvaluator,
    RequiredAdjacencySettings,
)
from .exceptions import (
    EvaluatorContractError,
    EvaluatorExecutionError,
    EvaluatorRegistrationError,
    FloorPlanScoringError,
    ScoringConfigurationError,
    ScoringInputError,
)
from .manager import FloorPlanScoreManager
from .registry import EvaluatorRegistry
from .types import (
    AESTHETIC_GROUP,
    CRITICAL_GROUP,
    EXTRA_GROUP,
    FUNCTIONAL_GROUP,
    EvaluationStatus,
    EvaluatorExecutionResult,
    EvaluatorKey,
    EvaluatorResult,
    FindingSeverity,
    FloorPlanScoringResult,
    GroupKey,
    GroupStatus,
    ScoreFinding,
    ScoreMetric,
    ScoringGroupResult,
)

__all__ = [
    "AESTHETIC_GROUP",
    "BEDROOM_QUALITY_KEY",
    "CRITICAL_GROUP",
    "DEFAULT_SCORING_PROFILE",
    "ENCLOSED_VOIDS_KEY",
    "EXTRA_GROUP",
    "FUNCTIONAL_GROUP",
    "GEOMETRY_INTEGRITY_KEY",
    "INWARD_RECESS_KEY",
    "KITCHEN_DINING_KEY",
    "LIVING_ROOM_BALANCE_KEY",
    "REQUIRED_ADJACENCY_KEY",
    "BedroomQualityEvaluator",
    "BedroomQualitySettings",
    "EnclosedVoidsEvaluator",
    "EnclosedVoidsSettings",
    "EvaluationStatus",
    "EvaluatorContractError",
    "EvaluatorExecutionError",
    "EvaluatorExecutionResult",
    "EvaluatorKey",
    "EvaluatorRegistrationError",
    "EvaluatorRegistry",
    "EvaluatorResult",
    "EvaluatorRule",
    "FindingSeverity",
    "FloorPlanScoreManager",
    "FloorPlanScoringError",
    "FloorPlanScoringResult",
    "FloorPlanEvaluator",
    "GeometryIntegrityEvaluator",
    "GeometryIntegritySettings",
    "GroupKey",
    "GroupStatus",
    "InwardRecessEvaluator",
    "InwardRecessSettings",
    "KitchenDiningEvaluator",
    "KitchenDiningSettings",
    "LivingRoomBalanceEvaluator",
    "LivingRoomBalanceSettings",
    "RequiredAdjacencyEvaluator",
    "RequiredAdjacencySettings",
    "ScoreFinding",
    "ScoreMetric",
    "ScoringConfigurationError",
    "ScoringContext",
    "ScoringContextFactory",
    "ScoringGroupResult",
    "ScoringGroupRule",
    "ScoringInputError",
    "ScoringProfile",
    "create_default_profile",
    "create_default_registry",
    "score_floor_plan",
]
